on:
  push:
    branches:
    - "docker-action-demo"
  workflow_dispatch:
    inputs:
      echoMessage:
        type: string
        description: 'echoMessage'
        required: false
        default: 'World'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Set env variable for workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "echoMessage=${{ github.event.inputs.echoMessage }}" >> $GITHUB_ENV
      - name: hello with Manualinput
        id: hello-manual
        with:
          echoMessage: 'manualInputString'
        uses: puglao/gha-docker-demo@master
      # Use the output from the `hello` step
      - name: Get the output hash
        run: echo "Hash of ${echoMessage} is ${{ steps.hello-manual.outputs.runHex }}"
      - name: hello with default
        id: hello-default
        uses: puglao/gha-docker-demo@master
      # Use the output from the `hello` step
      - name: Get the output hash
        run: echo "Hash of ${echoMessage} is ${{ steps.hello-default.outputs.runHex }}"