on:
  push:
    branches:
    - "docker-action-demo"
  workflow_dispatch:
    inputs:
      echoMessage:
        type: string
        description: 'echoMessage'
        required: false
        default: 'World'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: puglao/gha-docker-demo@v1
        with:
          echoMessage: 'puglao'
      # Use the output from the `hello` step
      - name: Get the output hash
        run: echo "The time was ${{ steps.hello.outputs.runHex }}"